---
- hosts: webservers
  become: true
  tasks:
    - name: Install package git
      yum:
        name: git
        state: present

    - name: Install package vsftpd
      yum:
        name: vsftpd
        state: present

    - name: Start vsftpd service
      service:
        name: vsftpd
        state: started
